name: SwiftyScepBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme SwiftyScep
    - name: Run tests
      run: swift test -v
    - name: Build and test ( macOS 12.0 Monterey)
      run: xcodebuild test -scheme SwiftyScep -destination 'platform=macOS,arch=x86_64,id=4666018E-420F-C1B5-9525-B145CECA79EB'
    - name: Build and test ( mac Catalyst 12.0)
      run: xcodebuild test -scheme SwiftyScep -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4666018E-420F-C1B5-9525-B145CECA79EB'
    - name: Build and test ( tvOS 15.0)
      run: xcodebuild test -scheme SwiftyScep -destination 'platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme SwiftyScep -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
    - name: Build and test ( watchOS 8.0)
      run: xcodebuild test -scheme SwiftyScep -destination 'platform=watchOS Simulator,OS=8.0,name=Apple Watch Series 6 - 40mm'
